### PR TITLE
Add support for Intel BLE Adapter

### LINKED ISSUE #3: Following issue 233 from Noble : compatibility with Intel adapter
Following issue https://github.com/sandeepmistry/noble/issues/233

After having read some part of the linux BT drivers, it seems obvious that the Intel adapters work a bit differently from other one. To have them work they ;

1) Put the adapter in "developer mode" to get the firmware
2) Patch the firmware and reinject it
3) Reset the adapter (it seems to be a special command to reset as well).

https://github.com/torvalds/linux/blob/master/drivers/bluetooth/btusb.c

I'm gonna try to reproduce the same thing adapting your work on this repo (and thx to the "usb" thing in node.js) but I'm afraid it's a bit beyond my field so help would be welcome :)

Anyway, I guess Intel adapters represent a decent chunk of the market and everyone will be happy to use them :) !

Keep you posted.

### PR DESCRIPTION
**Pull request by urish**
Should fix #3. Tested on 3 both Dell and Toshiba PCs with internal Intel BLE adapter, both running Windows 10.

### CODE REVIEW

**Comment by sandeepmistry** [comment]
@urish thanks!

**Comment by urish** [comment]
Thank you Sandeep! 

Two things I noted so far:

1. The adapter can't scan and connect at the same time, similar to sandeepmistry/noble#165. It seems like in some cases, you even need to set a small timeout between the `stopScanning()` and the `connect()` calls.
2. When connected to a device, terminating the process with Ctrl+C and starting it again seem to fail. I haven't investigated much, but seems like reinstalling the WinUSB driver with Zadig revives the adapter.

**Comment by urish** [comment]
@sandeepmistry any chance for a new release? 
I hope to use it in a workshop I'm running next week :-)

Thanks!

**Comment by sandeepmistry** [comment]
I've published v0.5.0 to npm with your changes.

> The adapter can't scan and connect at the same time, similar to sandeepmistry/noble#165. It seems like in some cases, you even need to set a small timeout between the stopScanning() and the connect() calls.

Interesting, I still haven't figured out if this is due to different interpretations of the HCI spec. and firmware implementation.

What if you pass a callback into `noble.stopScanning()` then call `connect()`?

> When connected to a device, terminating the process with Ctrl+C and starting it again seem to fail. I haven't investigated much, but seems like reinstalling the WinUSB driver with Zadig revives the adapter

Please create a new issue, when you have more details for this. Btw, noble attempts to listen for Ctrl-C [here](https://github.com/sandeepmistry/noble/blob/master/lib/hci-socket/bindings.js#L86-L102).

**Comment by urish** [comment]
Thank you so much for publishing the new version! 

I will try the thing with the `stopScanning()` callback and report back. 

Any ideas how to investigate the 2nd issue other than setting `DEBUG=*`? Perhaps some way to compile libusb with additional debug output?

**Comment by sandeepmistry** [comment]
You're welcome!

> Any ideas how to investigate the 2nd issue other than setting DEBUG=*? Perhaps some way to compile libusb with additional debug output

Not too sure about this, I'm not a full-time Window's user. Could you share more details on what you mean by "starting it again seem to fail"? Let's start a new issue to track this :)

**Comment by urish** [comment]
Alright, I will try to gather additional details and open a second issue

**Pull request merged**
