### PR TITLE
[WIP] Upgrade all the things, and change many things.

### PR DESCRIPTION
**Pull request by ghost**
I expect most everything here to be cherrypicked or redone and generally not merged as is.

 Some of this is already done in other PRs.

 Overview

 * Require at least node 6.x
 * Use eslint over jshint
 * Fix code style issues from a (mostly) default config with `eslint:recommended`
 * Include `examples/` in the lint
 * Upgrade node-gyp for (future) N-API support
 * Upgrade other dependencies for security issues (via `npm audit`)
 * Fix binding install path 
 * Rename binding to `bluetooth_hci_socket`
 * a build fix for Node 10.x (related to `errorConstructor`)
 * Add Node 8.x, 10.x, and 12.x to the build matrices
 * Rename `appveyor.yml` to `.appveyor.yml`
 * use let/const throughout
 * replace deprecated `Buffer` constructor usage

More to come.

### CODE REVIEW

**Comment by mhammerc** [comment]
Hello, many thanks for the great work!!

Any plans for merging this pull request?

**Comment by ghost** [comment]
@mhammerc this one shouldn't be merged. I just put it all together until anyone is ready to merge even bits of it. After that I will split out the pieces that folks find acceptable.

**Comment by ghost** [comment]
It now builds on node 12.x.

**Comment by rzr** [comment]
Please can you  forward this change to:

https://github.com/abandonware/node-bluetooth-hci-socket/

FYI an updated version has been released:

https://www.npmjs.com/package/@abandonware/bluetooth-hci-socket/v/0.5.3-5

**Pull request closed without merging**
