### PR TITLE
[WIP] Fix build on node 10.x

### PR DESCRIPTION
**Pull request by ghost**
This fix comes from
https://github.com/noble/node-bluetooth-hci-socket/issues/84#issuecomment-391951781
,  so I can't personally vouch for it.

### CODE REVIEW

**Comment by yourealwaysbe** [comment]
Thanks for this.  To get it to work i had to edit the package.json path lib/notify.js to start with ../

**Comment by ghost** [comment]
lib/notify where?

**Comment by yourealwaysbe** [comment]
Oops, sorry.  I meant [lib/native.js](https://github.com/jrobeson/node-bluetooth-hci-socket/blob/master/lib/native.js).

Took this from [a commit](https://github.com/kounch/node-bluetooth-hci-socket/commit/abddcad93ebf05df28afe6605b625625684f3fcc) in kounch's repo.

**Comment by ghost** [comment]
I'll add that, but I'm also working on a massive refactoring of the repo.

**Comment by ghost** [comment]
done

**Comment by matthewhague** [comment]
Thanks!

**Comment by notabene00** [comment]
Неплохо бы уже заиметь поддержку десятой ноды, да.

**Comment by rzr** [comment]
It worked for me, but I had to disable parallel building:

    MAKEFLAGS=-j1 npm install https://github.com/jrobeson/node-bluetooth-hci-socket/#fix-builds-for-node-10

Probably not related to that patch.

**Comment by rzr** [comment]
This is affecting "usb" module too, workaround is:

    cd node_modules/usb/ &&  MAKEFLAGS=-j1 npm install https://github.com/jrobeson/node-bluetooth-hci-socket/#fix-builds-for-node-10


This patch would be welcome in next release:
https://github.com/noble/node-bluetooth-hci-socket/issues/85

**Comment by Apollon77** [comment]
Are there any news? Last is one month ago ... when it is planned to be available?

**Comment by rzr** [comment]
meanwhile this can be forked into npm 'org namespace do you recommend any ?

**Comment by rzr** [comment]
meanwhile this can be forked into npm 'org namespace do you recommend any ?

**Comment by petersaints** [comment]
Node 10 has now reached LTS status, is there any official fix coming?

**Comment by rzr** [comment]
Is upstream ready to merge this change for supporting current node LTS?
I am a bit concerned because last change from master was in april.

Let's try to push a simple change to see how active is project:
https://github.com/noble/node-bluetooth-hci-socket/pull/102

Relate-to: https://github.com/noble/node-bluetooth-hci-socket/issues/84

**Comment by ghost** [comment]
I think sandeep is just too busy to properly maintain noble. I'm using my own typescriptified fork of noble instead.

**Comment by rzr** [comment]
So single maintenance model can be transferred to co-maintenance ? 

Any opinion on @sandeepmistry on this suggestion?

**Comment by AlCalzone** [comment]
Please merge :(

**Comment by rzr** [comment]
Released in

https://www.npmjs.com/package/@abandonware/bluetooth-hci-socket/v/0.5.3-0

**Comment by rzr** [comment]
Feel free to comment this related ticket:

https://github.com/abandonware/node-bluetooth-hci-socket/issues/9

**Pull request closed without merging**
